/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'SF Mono', 'Consolas', 'monospace'],
      },
      colors: {
        canvas: {
          app:      'var(--canvas-app)',
          sidebar:  'var(--canvas-sidebar)',
          panel:    'var(--canvas-panel)',
          elevated: 'var(--canvas-elevated)',
          overlay:  'var(--canvas-overlay)',
        },
        label: {
          primary:     'var(--label-primary)',
          secondary:   'var(--label-secondary)',
          'secondary-on-fill': 'var(--label-secondary-on-fill)',
          tertiary:    'var(--label-tertiary)',
          placeholder: 'var(--label-placeholder)',
        },
        fill: {
          primary:   'var(--fill-primary)',
          secondary: 'var(--fill-secondary)',
          hover:     'var(--fill-hover)',
          active:    'var(--fill-active)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          fill:    'var(--accent-fill)',
          border:  'var(--accent-border)',
          text:    'var(--accent-text)',
        },
        separator:          'var(--separator)',
        'separator-opaque': 'var(--separator-opaque)',
        status: {
          success:        'var(--status-success)',
          warning:        'var(--status-warning)',
          error:          'var(--status-error)',
          info:           'var(--status-info)',
          'success-fill':   'var(--status-success-fill)',
          'success-border': 'var(--status-success-border)',
          'warning-fill':   'var(--status-warning-fill)',
          'warning-border': 'var(--status-warning-border)',
          'error-fill':     'var(--status-error-fill)',
          'error-border':   'var(--status-error-border)',
          'info-fill':      'var(--status-info-fill)',
          'info-border':    'var(--status-info-border)',
        },
        method: {
          get:     'var(--method-get)',
          post:    'var(--method-post)',
          put:     'var(--method-put)',
          patch:   'var(--method-patch)',
          delete:  'var(--method-delete)',
          head:    'var(--method-head)',
          options: 'var(--method-options)',
        },
      },
      borderRadius: {
        xs:      '3px',
        sm:      '7px',
        DEFAULT: '10px',
        md:      '10px',
        lg:      '14px',
        xl:      '18px',
        '2xl':   '24px',
        full:    '9999px',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.25, 0, 0, 1)',
        enter:    'cubic-bezier(0, 0, 0, 1)',
        exit:     'cubic-bezier(0.32, 0, 0.67, 0)',
        spring:   'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        micro:    '60ms',
        quick:    '120ms',
        standard: '240ms',
        enter:    '300ms',
        exit:     '180ms',
        spring:   '400ms',
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
};
